# Render deployment configuration file for backend service

services:
  # Backend service
  - type: web
    name: memorix-backend
    env: node
    buildCommand: npm install
    startCommand: npm  start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Explicitly set a port for Render
      - key: FRONTEND_URL
        value: https://memorix.fun   # Set to your frontend domain
      - key: MONGO_URI
        fromDatabase:
          name: memorix-db
          property: connectionString
    plan: starter  # Choose the appropriate plan based on your needs

# Add database if needed
databases:
  - name: memorix-db
    databaseName: memorix
    plan: starter # Choose the appropriate database plan
